### ISSUE TITLE
ssl.SSLError: [SSL: HTTP_REQUEST] http request

### ISSUE THREAD

**Issue by zhouhao3** [openshift/cluster-baremetal-operator#152]
When using OCP version 4.8.0-0.nightly-2021-03-19-184028 to deploy bare metal by IPI, The master can be deployed successfully, but the worker is always in the inspecting state when deploying the worker. Check the inspector log to get the following error message.
``` 
1294 Traceback (most recent call last):
 1295   File "/usr/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 461, in fire_timers
 1296     timer()
 1297   File "/usr/lib/python3.6/site-packages/eventlet/hubs/timer.py", line 59, in __call__
 1298     cb(*args, **kw)
 1299   File "/usr/lib/python3.6/site-packages/eventlet/greenthread.py", line 221, in main
 1300     result = function(*args, **kwargs)
 1301   File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 818, in process_request
 1302     proto.__init__(conn_state, self)
 1303   File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 357, in __init__
 1304     self.handle()
 1305   File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 390, in handle
 1306     self.handle_one_request()
 1307   File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 419, in handle_one_request
 1308     self.raw_requestline = self._read_request_line()
 1309   File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 402, in _read_request_line
 1310     return self.rfile.readline(self.server.url_length_limit)
 1311   File "/usr/lib64/python3.6/socket.py", line 586, in readinto
 1312     return self._sock.recv_into(b)
 1313   File "/usr/lib/python3.6/site-packages/eventlet/green/ssl.py", line 241, in recv_into
 1314     return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
 1315   File "/usr/lib/python3.6/site-packages/eventlet/green/ssl.py", line 256, in _base_recv
 1316     read = self.read(nbytes, buffer_)
 1317   File "/usr/lib/python3.6/site-packages/eventlet/green/ssl.py", line 176, in read
 1318     super(GreenSSLSocket, self).read, *args, **kwargs)
 1319   File "/usr/lib/python3.6/site-packages/eventlet/green/ssl.py", line 150, in _call_trampolining
 1320     return func(*a, **kw)
 1321   File "/usr/lib64/python3.6/ssl.py", line 833, in read
 1322     return self._sslobj.read(len, buffer)
 1323   File "/usr/lib64/python3.6/ssl.py", line 590, in read
 1324     v = self._sslobj.read(len, buffer)
 1325 ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:2354)
```
After investigation, it is found that when deploying the worker, the IPA on the worker uses the http protocol, but the ipa-api-url used by the ironic in the cluster is the https protocol, which should be the cause of this error.
```
ipa-api-url=https://192.168.20.3:6385
```
Because the protocols on both sides are the same when deploying the Master (both are http), the Master can be deployed successfully.

btw, this issue appeared after this [commit](https://github.com/openshift/cluster-baremetal-operator/commit/671e334d95ed2a17d0e8eef5c6d8357431512a45) was merged.

**Comment by rhjanders** [comment]
@zhouhao3 do I understand correctly this is fixed with https://github.com/openshift/cluster-baremetal-operator/pull/156 and hence can be closed? Thank you.

**Comment by zhouhao3** [comment]
@rhjanders  yes, I'll close, thanks!
